networks:
  financialNetwork:
    driver: bridge

services:

  database:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=finanManag
      - POSTGRES_PASSWORD=YMgKAwcbtNdJiphuaeAlytxMx
      - POSTGRES_DB=financial_db
      #volumes:
      #- postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U finanManag -d financial_db" ]
      interval: 8s
      timeout: 3s
      retries: 2
    networks:
      - financialNetwork

  api: &api
    build: ../
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - financialNetwork

  api02:
    <<: *api
    ports:
      - "8081:8080"

  create_tables:
    image: postgres:17.2
    depends_on:
      - api
    volumes:
      - ../db/create_tables_v1.sql:/docker-entrypoint-initdb.d/create_tables_v1.sql
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        echo "Waiting for the database to be ready..."
        sleep 40
        echo "Executing create_tables_v1.sql..."
        PGPASSWORD="YMgKAwcbtNdJiphuaeAlytxMx" \
        psql -h database -U finanManag -d financial_db -f /docker-entrypoint-initdb.d/create_tables_v1.sql
    restart: "no"
    networks:
      - financialNetwork

  load_balancer:
    image: nginx:1.27
    ports:
      - "80:80"
    depends_on:
      - api
      - api02
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - financialNetwork

volumes:
  postgres_data:
